#' Daframe of raw data of the blenderFace package
#' 
#' The data frame contains coordinates of facial movements over four stimulus 
#' conditions of two subjects. The data frame was generated by the function
#' *blenderFace::concatData()*. The measurements of the movement is in Blender
#' units (BU).
#' 
#' @format A data frame with 51 variables and 3406 rows:
#' describe{
#'  \item{AU_01_L_x -- AU_16_z}{Marker movement of the tracked markers in 
#'  Blender units}
#'  \item{Frame}{Framenumber of the tracked video clip}
#'  \item{Stimulustype}{Type of instructions presented to the subjects. 
#'  Posed neutral = dont show any emotional expression, 
#'  posed disgust = show a disgusted facial expression, 
#'  posed happiness = show a happy facial expression, 
#'  posed fear = show an anxious facial expression}
#'  \item{subject}{Subject number}
#' }
#' @source Demo video is in the supplemental material of the article fix_me
"rawdata"
