#' Plot markers on symbolic head
#' 
#' Plots symbolic standardized head with markers plotted on predefined areas. 
#' Be sure to use standardized data, done by the functions \code{\link{bu2mm}}
#' and \code{\link{face2stdFace}}.
#' 
#' @param data Data-frame with a row sequence of *standardized* x/y
#'   coordinates for each marker. Please use the functions 'ScaleBlenderData' 
#'   and 'ScaleFaceData' before plotting the data. Names of the data columns 
#'   must and in '_x' for the x-axis and in '_y' for the y-axis.
#' @param dataPos numeric vector with x/y starting coordinates each marker
#'   should be plotted on the face. This vector can also be generated by using 
#'   the offsetTable generated by the function CenterCond(). Due to the tracking
#'   procedure in blender, the center of the coordinate system is the nose tip 
#'   at x = 0, y = 0. Scaling of the data to fit the plot is done automatically 
#'   based on max./min. values of data columns.
#' @param scaleFactor Factor which is used to rescale data for x-head. Should be
#' a positive integer (e.g., 2000)
#' @param title Default is no title.
#' @param color character vector of lenght one to define the color for plotting
#'   the Marker. Default is 'black'.
#' @param alpha alpha value / density for marker plots. 0 represents full 
#' transparency, whereas 1 represents full color. Default = .50.
#' @param overplot If TRUE, only the marker plots, but no base graph is plotted.
#'   Default is FALSE.
#'   
#' @return nice X-head plot with aggregated marker movements
#'   
#' @author Rainer Alexandrowicz, Axel Zinkernagel
#'   \email{rainer.alexandrowicz@aau.at, zinkernagel@uni-landau.de}
#'   
#' @examples
#' \dontrun{plotMarkerXHead()}
#' 
#' @export
plotMarkerXHead <- function(data, dataPos, scaleFactor, title = "Square Head Baseplot", overplot = FALSE, color = "black", alpha = 0.5) {
    # Error handling
    if (!(nrow(data)) > 0 | !(is.data.frame(data))) {
        stop("Argument data is missing or of incorrect type!")
    }
    if (!(is.numeric(dataPos)) | (length(dataPos) != ncol(data))) {
        stop("Argument dataPos is not numeric or not of equal length as data matrix/dataframe!")
    }
    if (!(is.numeric(scaleFactor)) | !(scaleFactor > 0)) {
        stop("Argument scaleFactor is not numeric or not positive!")
    }
    if (!(is.character(title))) {
        stop("Argument title is not of type character!")
    }
    if (!(is.character(color))) {
        stop("Argument color is of incorrect type!")
    }
    if (!(is.numeric(alpha) | alpha < 0 | alpha > 1)) {
        stop("Argument alpha is not of type numeric between 0 and 1!")
    }
    if (!(is.logical(overplot))) {
        stop("Argument overplot is not of type logical!")
    }
    
    plotBaseXHead <- function() {
        # min for all x/y-Markers is -75, max for all x/y-Markers is 97
        plot(0:1, 0:1, xlim = c(-100, 100), ylim = c(-100, 100), type = "n", axes = F, main = title, xlab = "", ylab = "")  # plot area
        box()
        abline(h = 0, col = grey(0.8), lty = 3)  # horizontal axis
        abline(v = 0, col = grey(0.8), lty = 3)  # vertical axis
        
        # using the nose as center, as it is done in blender measurement
        points(0, 0, pch = 24, cex = 2, col = 1)  # nose (at the center)
        
        points(-50, 50, pch = 1, cex = 1.5)  # left eye
        points(50, 50, pch = 1, cex = 1.5)  # right eye
        points(-50, 50, pch = 16, cex = 0.7)  # left pupil
        points(50, 50, pch = 16, cex = 0.7)  # right pupil
        
        segments(-30, -70, 30, -70, lwd = 2)  # mouth line
    }
    
    # using fixed scale factor to have an equal scaling for all plots
    dataPos <- dataPos * scaleFactor
    data <- data * scaleFactor
    
    # add offset value for each marker to position marker to the correct position of the x-head
    tempData <- sweep(data, MARGIN = 2, dataPos, FUN = "+")
    
    # plot base square head
    if (!overplot) {
        plotBaseXHead()
    }
    
    # recompute and add alpha/transparency value to color settings
    color <- c(as.numeric(col2rgb(color)), alpha * 255)
    color <- rgb(color[1], color[2], color[3], color[4], maxColorValue = 255)
    
    # Plot markers on square head
    for (i in 1:(ncol(tempData)/2)) {
        points(as.numeric(unlist(tempData[(i * 2) - 1])), as.numeric(unlist(tempData[i * 2])), pch = 16, col = color, cex = 0.2)
    }
}
